// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19nRyZ3qEiLwKD1e4i75Y8lBgO-NyO0Q',
    appId: '1:529528003363:web:f186039ef4d0b7f2ca0a96',
    messagingSenderId: '529528003363',
    projectId: 'uoh-master-project-21066202',
    authDomain: 'uoh-master-project-21066202.firebaseapp.com',
    storageBucket: 'uoh-master-project-21066202.appspot.com',
    measurementId: 'G-CMK0T36QZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB24pwl0rf8HCoBlXmfD3b5OeKaZgmBX04',
    appId: '1:529528003363:android:db198cda34d08bc2ca0a96',
    messagingSenderId: '529528003363',
    projectId: 'uoh-master-project-21066202',
    storageBucket: 'uoh-master-project-21066202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_U7CEg6VFrsXsGwSVsBehq8-stA9XEho',
    appId: '1:529528003363:ios:931782ce7708dacdca0a96',
    messagingSenderId: '529528003363',
    projectId: 'uoh-master-project-21066202',
    storageBucket: 'uoh-master-project-21066202.appspot.com',
    iosClientId: '529528003363-4i0da0gtrq5nc3lmltqtk7j2b68f8oms.apps.googleusercontent.com',
    iosBundleId: 'com.winglamtsang.masterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_U7CEg6VFrsXsGwSVsBehq8-stA9XEho',
    appId: '1:529528003363:ios:ea0ddd03426452f9ca0a96',
    messagingSenderId: '529528003363',
    projectId: 'uoh-master-project-21066202',
    storageBucket: 'uoh-master-project-21066202.appspot.com',
    iosClientId: '529528003363-f7mnfb2mmrfkfe4552pi4g5irusl3n7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.sourceCode',
  );
}
